[package]
name = "binding_rust"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc="*"

[dependencies]
tree-sitter = "0.22.6"
tree-sitter-rust = "0.21.2"

